#!/bin/bash

set -e

# Parse image name for repo name
tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}
shortCommit=${SOURCE_COMMIT:0:7}


# Tag and push image for each additional tag
#for tag in {latest,another}; do
#    docker tag $IMAGE_NAME ${repoName}:${tag}
#    docker push ${repoName}:${tag}
#done

docker tag $IMAGE_NAME ${repoName}:${shortCommit}
docker push ${repoName}:${shortCommit}

